# Generated by Django 3.1.4 on 2020-12-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='onecar_id',
        ),
    ]
