# Generated by Django 3.1.4 on 2020-12-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20201210_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
