# Generated by Django 3.1.2 on 2020-12-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car_id',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
