# Generated by Django 3.1.2 on 2020-12-18 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20201218_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(null=True)),
                ('service_name', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('confirm', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='car_request',
            name='car_id',
            field=models.IntegerField(null=True),
        ),
    ]
