# Generated by Django 3.1.2 on 2020-12-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20201219_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_request',
            name='service_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
