# Generated by Django 3.1.2 on 2020-12-21 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_services',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='our_services',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
