# Generated by Django 3.1.2 on 2020-12-21 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0002_auto_20201222_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_services',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='our_services',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
