# Generated by Django 3.1.2 on 2020-12-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0003_auto_20201222_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_services',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
