# Generated by Django 3.1.4 on 2020-12-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlists', '0002_auto_20201208_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_listings',
            old_name='is_published',
            new_name='is_Available',
        ),
    ]
