# Generated by Django 3.1.2 on 2020-12-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlists', '0003_auto_20201208_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_listings',
            name='extra_message',
            field=models.CharField(max_length=80),
        ),
    ]
